export class ColorConstants {
  static readonly PURE_BLACK: Resource = $r('app.color.pure_black');
  static readonly PURE_WHITE: Resource = $r('app.color.pure_white');
  static readonly INTERNATIONAL_ORANGE: Resource = $r('app.color.international_orange');
  static readonly TUNDORA: Resource = $r('app.color.tundora');
  static readonly MINE_SHAFT: Resource = $r('app.color.mine_shaft');
  static readonly COD_GRAY: Resource = $r('app.color.cod_gray');
  static readonly CERULEAN: Resource = $r('app.color.cerulean');
  static readonly CHATEAU_GREEN: Resource = $r('app.color.chateau_green');
  static readonly SCARLET: Resource = $r('app.color.scarlet');
}
